require("prototypes.groups")
require("prototypes.item")
require("prototypes.equipment")
require("prototypes.recipe")
require("prototypes.technology")
require("prototypes.entity")
require("prototypes.shortcuts")
require("prototypes.tips")
