data:extend({
  {type = "recipe-category", name = "harvesting"},
  {type = "recipe-category", name = "armor-forging"},
})

data:extend({
  {
    type            = "recipe",
    name            = "aquilo-prom-suit-component",
    enabled         = false,
    energy_required = 5,
    ingredients = {
      {type = "item", name = "steel-plate", amount = 2},
    },
    results = {{type = "item", name = "aquilo-prom-suit-component", amount = 1}},
  },
  {
    type            = "recipe",
    name            = "mech-armor-mk2",
    enabled         = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "mech-armor",                   amount = 1},
      {type = "item", name = "steel-plate",                  amount = 5},
      {type = "item", name = "bio-interface",                amount = 1},
      {type = "item", name = "aquilo-prom-suit-component",   amount = 1},
      {type = "item", name = "promethium-armor-chassis",     amount = 1},
      {type = "item", name = "promethium-asteroid-chunk",    amount = 100},
      {type = "item", name = "promethium-armor-electronics", amount = 1},
    },
    results = {{type = "item", name = "mech-armor-mk2", amount = 1}},
  },
  {
    type            = "recipe",
    name            = "promethium-armor-chassis",
    enabled         = false,
    energy_required = 30,
    category        = "armor-forging",
    ingredients = {
      {type = "item", name = "demolisher-heart", amount = 1},
      {type = "item", name = "tungsten-plate",   amount = 100},
      {type = "item", name = "steel-plate",      amount = 100},
    },
    results = {{type = "item", name = "promethium-armor-chassis", amount = 1}},
  },
  {
    type            = "recipe",
    name            = "promethium-armor-electronics",
    enabled         = false,
    energy_required = 60,
    category        = "armor-forging",
    ingredients = {
      {type = "item", name = "charged-lightning-gem",  amount = 10},
      {type = "item", name = "speed-module-3",         amount = 5},
      {type = "item", name = "efficiency-module-3",    amount = 5},
      {type = "item", name = "productivity-module-3",  amount = 5},
      {type = "item", name = "quality-module-3",       amount = 5},
    },
    results = {{type = "item", name = "promethium-armor-electronics", amount = 1}},
  },
  {
    type = "recipe",
    name = "regenerative-plating",
    enabled = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "energy-shield-equipment", amount = 1},
      {type = "item", name = "steel-plate", amount = 10},
    },
    results = {{type = "item", name = "regenerative-plating", amount = 1}},
  },
  {
    type = "recipe",
    name = "personal-combat-roboport",
    enabled = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "defender-capsule",              amount = 200},
      {type = "item", name = "combat-roboport",               amount = 1},
      {type = "item", name = "personal-roboport-mk2-equipment", amount = 1},
      {type = "item", name = "speed-module-3",                amount = 2},
      {type = "item", name = "efficiency-module-3",           amount = 2},
      {type = "item", name = "gun-turret",                    amount = 5},
    },
    results = {{type = "item", name = "personal-combat-roboport", amount = 1}},
  },
  {
    type = "recipe",
    name = "personal-combat-roboport-distractor",
    enabled = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "distractor-capsule",            amount = 200},
      {type = "item", name = "combat-roboport",               amount = 1},
      {type = "item", name = "personal-roboport-mk2-equipment", amount = 1},
      {type = "item", name = "speed-module-3",                amount = 2},
      {type = "item", name = "efficiency-module-3",           amount = 2},
      {type = "item", name = "laser-turret",                  amount = 5},
    },
    results = {{type = "item", name = "personal-combat-roboport-distractor", amount = 1}},
  },
  {
    type = "recipe",
    name = "personal-robot-stash",
    hidden = true,
    enabled = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "construction-robot", amount = 5},
      {type = "item", name = "steel-chest",        amount = 1},
    },
    results = {{type = "item", name = "personal-robot-stash", amount = 1}},
  },
  {
    type = "recipe",
    name = "personal-beacon-equipment",
    enabled = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "beacon",      amount = 1},
      {type = "item", name = "steel-plate", amount = 10},
    },
    results = {{type = "item", name = "personal-beacon-equipment", amount = 1}},
  },
  {
    type = "recipe",
    name = "personal-combat-roboport-destroyer",
    enabled = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "destroyer-capsule",             amount = 200},
      {type = "item", name = "combat-roboport",               amount = 1},
      {type = "item", name = "personal-roboport-mk2-equipment", amount = 1},
      {type = "item", name = "speed-module-3",                amount = 2},
      {type = "item", name = "efficiency-module-3",           amount = 2},
      {type = "item", name = "tesla-turret",                  amount = 2},
    },
    results = {{type = "item", name = "personal-combat-roboport-destroyer", amount = 1}},
  },
  {
    type = "recipe",
    name = "pocket-dimension-generator",
    enabled = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "fusion-reactor-equipment", amount = 1},
      {type = "item", name = "steel-plate",              amount = 5},
    },
    results = {{type = "item", name = "pocket-dimension-generator", amount = 1}},
  },
  {
    type            = "recipe",
    name            = "armor-forging-station",
    enabled         = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "assembling-machine-3", amount = 1},
      {type = "item", name = "steel-plate",          amount = 10},
    },
    results = {{type = "item", name = "armor-forging-station", amount = 1}},
  },
  {
    type            = "recipe",
    name            = "bio-interface",
    enabled         = true,
    energy_required = 10,
    category        = "armor-forging",
    ingredients     = {{type = "item", name = "gleba-parts", amount = 10}},
    results         = {{type = "item", name = "bio-interface", amount = 1}},
  },
  {
    type            = "recipe",
    name            = "gleba-parts-from-biomass",
    enabled         = true,
    energy_required = 1,
    category        = "harvesting",
    ingredients     = {{type = "item", name = "enemy-biomass", amount = 1}},
    results         = {{type = "item", name = "gleba-parts",   amount = 1}},
  },
  {
    type            = "recipe",
    name            = "quantum-coil",
    enabled         = true,
    energy_required = 5,
    ingredients = {
      {type = "item", name = "iron-plate", amount = 1},
    },
    results = {{type = "item", name = "quantum-coil", amount = 1}},
  },
  {
    type            = "recipe",
    name            = "legochest",
    enabled         = true,
    energy_required = 5,
    ingredients = {
      {type = "item", name = "steel-plate", amount = 10, quality = "legendary"},
      {type = "item", name = "iron-plate",  amount = 5},
    },
    results = {{type = "item", name = "legochest", amount = 1}},
  },
  {
    type            = "recipe",
    name            = "harvester",
    enabled         = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "electronic-circuit", amount = 3},
      {type = "item", name = "iron-gear-wheel",    amount = 5},
      {type = "item", name = "iron-plate",         amount = 9},
    },
    results = {{type = "item", name = "harvester", amount = 1}},
  },
  {
    type            = "recipe",
    name            = "mind-control-rocket",
    enabled         = false,
    energy_required = 1,
    ingredients     = {{type = "item", name = "iron-plate", amount = 1}},
    results         = {{type = "item", name = "mind-control-rocket", amount = 1}},
  },
  {
    type             = "recipe",
    name             = "massive-lightning-collector",
    enabled          = false,
    energy_required  = 10,
    ingredients = {
      {type = "item", name = "lightning-collector", amount = 10},
    },
    results = {{type = "item", name = "massive-lightning-collector", amount = 1}},
  },
  {
    type = "recipe",
    name = "personal-tesla-turret",
    enabled = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "personal-laser-defense-equipment", amount = 1},
      {type = "item", name = "tesla-turret",                     amount = 1},
    },
    results = {{type = "item", name = "personal-tesla-turret", amount = 1}},
  },
  {
    type = "recipe",
    name = "personal-time-stopper",
    enabled = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "battery-mk2-equipment", amount = 1},
      {type = "item", name = "steel-plate",           amount = 10},
    },
    results = {{type = "item", name = "personal-time-stopper", amount = 1}},
  },
})

if mods["planet-rabbasca"] then
  data:extend({{
    type            = "recipe",
    name            = "personal-warp-pylon-equipment",
    enabled         = false,
    energy_required = 10,
    ingredients = {
      {type = "item", name = "rabbasca-warp-pylon",  amount = 2},
      {type = "item", name = "speed-module-3",       amount = 2},
      {type = "item", name = "efficiency-module-3",  amount = 2},
    },
    results         = {{type = "item", name = "personal-warp-pylon-equipment", amount = 1}},
  }})
end
